### ISSUE TITLE
Player isn't pulling clips after a certain date

### ISSUE THREAD

**Issue by flaminHotFledge** [teklynk/twitch_clips_player#16]
I've been noticing for a few streams now, an issue where the player is only playing old clips of mine. I looked into this further, and tried setting the date range to within the last 100 days, and am getting no clips returned. Tried clearing cache, editing settings, but nothing seems to be fixing this. It respects deleted clips, but It's only pulling clips from before I had started using this player. It refuses to pull any that have been made since then.

**Comment by teklynk** [comment]
Yes. This is related to this issue. https://github.com/teklynk/twitch_clips_player/issues/13 Twitch changed the way clips are served and it "broke" mostly all clips players and shoutout clips. The only workaround is to only display clips that use the old clips URL (before Twitch the change).

**Comment by flaminHotFledge** [comment]
Thank you for the reply! I was worried that might have been the case. Shall do it manually, now.

**Comment by teklynk** [comment]
@flaminHotFledge 

This "should" now be fixed but I do not know for how long since it uses yet another un-official way to get the clips from Twitch. With some help from the community and some reverse engineering we were able to figure out Twitch's (undocumented) graphql query. This however uses Twitch's client-id and graphql token. I do not know if Twitch will ever change these tokens over time. For now, It seems to be working!
