### ISSUE TITLE
clips limit

### ISSUE THREAD

**Issue by ASd3214ea** [teklynk/twitch_clips_player#4]
why is there 100 clips limit? Do clips refresh when you make the source visible in OBS?

**Comment by teklynk** [comment]
Twitch's API allows to pull 100 items at a time. In order to get the next 100 item, It requires doing another lookup/request. I will look into increasing this limit to maybe 300? The problem is that the response time could be slow if it has to do 3 requests to return a total of 300 items/clips. I hope that makes sense.

In OBS, set the browser source to: "Shutdown source when not visible" and "Refresh browser when scene becomes active". This will prevent the clips play from playing in the background. It will also reload/refresh the clip player when the source becomes active.

**Comment by ASd3214ea** [comment]
Okay, I understand the limit now.
The script can't pull random clips, only 100 most popular clips, right?
Thank you very much for answering

**Comment by teklynk** [comment]
Right, It only pulls the 100 most popular clips. Twitch's API sorts the clips by popularity as default. This top 100 list is dynamic and could be different over time. 

There is also the Date Range option that allows you to only show the Most Recent Clips from the last 30, 60, 90 days... This may be useful?

**Comment by ASd3214ea** [comment]
It's not exactly what I need but it's still cool
Really appreciate this player. Simple and easy to use. 
And thank you for answering!
